Practise\FuncBundle\Entity\Product:
    type: entity
    table: null
    repositoryClass: Practise\FuncBundle\Entity\ProductRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        sku:
            type: integer
        description:
            type: string
            length: 255
        price:
            type: integer
    manyToMany:
        categories:
            targetEntity: Category
            joinTable:
                name: product_category
                joinColumns:
                    product_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    category_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
